# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a9658d1b11e1f6b020ec4e2423427728401c48a2baf6617f365cc5162f60518b9a24eb961176137613cd271069f70f51817854a567359ab5005eabfd8b0cfd

test:
  secret_key_base: c404716432d30cb312e8364b4f1946534c1e9f0efb7a9bfd0d19b41cf1a99c7c53b38031f45e65aa5761ef50c0d5b9160305816a91a09be4ebb1c422e3672566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
